### ISSUE TITLE
Resource card component

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/livewire#1]
Create a `<Resource />` Vue.js component that encapsulates a resource listed in Livewire.

---

## User story
As a user, I want to see all relevant info about a resource at a glance, and be able to find out more information by clicking on related links so that I can decide if a tool fits my needs.

## Features:

- Title
- Description
- Link to GitHub repository
- Link to demo video (if exists)
- List of tags

## Mockups
![image](https://user-images.githubusercontent.com/127797/87777035-c9381700-c7f6-11ea-83be-aab42fe2dfaa.png)
![image](https://user-images.githubusercontent.com/127797/87776999-b0c7fc80-c7f6-11ea-9020-b907b75553b9.png)

**Comment by msangapu-msft** [comment]
We've got the major portion of this completed. Some minor adjustments needed.
