### ISSUE TITLE
✨[AddResource] Automatically hide add links if not clicked

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/livewire#24]
Automatically reset the `AddResource` component if you click on the **Add** button and do not click a link to add a resource.

## User story
As a user I want the UI to remain in a state that makes the most sense to me so that I'm confused as to how I am supposed to interact with the UI.

## Features
After clicking on the **Add** button, the *Repository | Extension* appear. If the user doesn't click on one of these links by the time three seconds has elapsed, then the UI should automatically reset itself by calling the `cancel` method.

**Comment by georgewallace** [comment]
@craigshoemaker created a PR https://github.com/craigshoemaker/livewire/pull/31 for this. Let me know if it meets quality standards..

**Comment by craigshoemaker** [comment]
Your PR was merged! 🎉
