### ISSUE TITLE
✨ [ExtensionCard] UI updates

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/livewire#28]
Update the `ExtensionCard` component UI.

## User story
As a user, I want to see information about each component and be able to click on the title to see the extension listing in the VS Code marketplace so that I can decide if this component suits my needs.

## Features

The component should feature: 

- Title should be a link to the extension (which opens in a new tab)
- Description

**Comment by msangapu-msft** [comment]
Hey @craigshoemaker,

I can extract title from RowKey using string manipulation. What about the description? Or can we insert this data into the object so I can query it w/o additional manipulation?

![image](https://user-images.githubusercontent.com/49697512/94845496-60b80980-03e5-11eb-90ea-21d3e1b7115e.png)

**Comment by craigshoemaker** [comment]
I will update the API to mock that data for you as I implement the logic to extract from the marketplace. I should have an update for you today on that

**Comment by craigshoemaker** [comment]
`extension` objects now have a `title` and `description` property with mock data

**Comment by msangapu-msft** [comment]
@craigshoemaker  Thanks for the quick turnaround!

**Comment by msangapu-msft** [comment]
PR is here: https://github.com/craigshoemaker/livewire/pull/30

It could use spacing between ExtensionCards.

**Comment by craigshoemaker** [comment]
PR #30 is merged 🎉
