### ISSUE TITLE
AppService Account

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/livewire#43]
- Create account
- Lock down with MS only security requirements
- CI/CD
- [optional] a way to expose the logged-in user alias to JavaScript

**Comment by msangapu-msft** [comment]
Created livewire.azurewebsites.net
Locked down with Azure Active Directory

Investigating CI/CD

**Comment by craigshoemaker** [comment]
Closing this issue as we are going to use Azure Static Web Apps for the UI (#49).
