### ISSUE TITLE
ResourceList component

### ISSUE THREAD

**Issue by craigshoemaker** [craigshoemaker/livewire#5]
Create a `ResourceList` Vue.js component to display results that reflect search terms and filter settings.

---

## User story
As a user, I want to see the filtered results against the full data set which reflect my selections in the filters and search terms so that I can find the resources I am looking for quickly.

## Features
- Displays a list of `ResourceCard` components that match the current search and filter criteria

## Mockups

![image](https://user-images.githubusercontent.com/127797/87778895-e4f0ec80-c7f9-11ea-9373-ac64d83cdd78.png)

**Comment by msangapu-msft** [comment]
Wohoo!! We're done here.
